DATA:
  VIDEO_DIR_PATH: /mnt/nas/datasets/ego4d-release1/fho_raw_videos
  ANN_PATH: /mnt/nas/datasets/ego4d-release1/FHO_extract_updated_complete_frame_number_update.json
  SPLIT_PATH: /mnt/nas/datasets/ego4d-release1/temp_split.json
  CLIPS_SAVE_PATH: /mnt/hdd/datasets/ego4d-release1/release1_extracted_clips_21-08-21
  VIDEO_LOCATIONS_CSV: /mnt/nas/datasets/ego4d-miniset/consortium-sharing/dataset_manifests/video_component_locations_university_video_access_release1.csv
  NO_SC_PATH: /mnt/hdd/datasets/ego4d-release1/release1_extracted_negative_clips_23-08-21
  SAMPLING_FPS: 2
  CLIP_LEN_SEC: 8
  DECODING_BACKEND: pyav
  TARGET_FPS: 30
  NUM_FRAMES: 0
  CROP_SIZE: 225
  TASK: "state_change_detection_and_keyframe_localization"
TRAIN:
  TRAIN_ENABLE: True
  DATASET: Ego4DKeyframeLocalisation
  BATCH_SIZE: 4
TEST:
  ENABLE: True
  BATCH_SIZE: 4
  JSON: fixed_test_set.json
  VAL_JSON: fixed_val_set.json
DATA_LOADER:
  NUM_WORKERS: 36
  PIN_MEMORY: True
  SHUFFLE: True
  ENABLE_MULTI_THREAD_DECODE: True
  SOFT_LABELS: False
  IS_NO_STATE_CHANGE: False
MISC:
  VERBOSE: False
  FAST_DEV_RUN: False
  NUM_GPUS: 2
  OUTPUT_DIR: /home/sid/benchmark/release1_clips_extraction
  TEST_TRAIN_CODE: False
MODEL:
  ARCH: "slow_layer3"
  NUM_CLASSES: [1]
  HEAD_ACT: softmax
  MODEL_NAME: DualHeadResNet
SOLVER:
  BASE_LR: 0.0001
  MAX_EPOCH: 1000
