DATA:
  VIDEO_DIR_PATH: /mnt/nas/datasets/ego4d-release1/fho_canonical_videos_24-08-21
  ANN_PATH: /home/abrsh/canonical_dataset/fho_pre_period_draft_updated_schema_tested.json
  SPLIT_PATH: /home/abrsh/canonical_dataset/split
  CLIPS_SAVE_PATH: /mnt/hdd/datasets/ego4d-release1/fho_canonical_extracted_frames_27-08-21
  VIDEO_LOCATIONS_CSV: /home/abrsh/canonical_dataset/manifest.csv
  NO_SC_PATH: /mnt/hdd/datasets/ego4d-release1/fho_canonical_extracted_frames_negative_clips_27-08-21
  NO_SC_SPLIT_PATH: /home/sid/canonical_dataset/negative_clips_splits_json_2021-09-17.json
  SAMPLING_FPS: 2
  CLIP_LEN_SEC: 8
  DECODING_BACKEND: pyav
  TARGET_FPS: 30
  INPUT_CHANNEL_NUM: [ 3, 3 ]
  NUM_FRAMES: 0
  CROP_SIZE: 224
  TASK: "state_change_detection"
TRAIN:
  TRAIN_ENABLE: True
  DATASET: CanonicalKeyframeLocalisation_v2
  BATCH_SIZE: 2
TEST:
  ENABLE: True
  BATCH_SIZE: 4
  JSON: /home/abrsh/canonical_dataset/fixed_test_set_canonical_17-09-21.json
  VAL_JSON: /home/sid/canonical_dataset/fixed_val_set_canonical_17-09-21.json
  DATASET: CanonicalKeyframeLocalisation_v2
DATA_LOADER:
  NUM_WORKERS: 36
  PIN_MEMORY: True
  SHUFFLE: True
  ENABLE_MULTI_THREAD_DECODE: True
  SOFT_LABELS: False
  IS_NO_STATE_CHANGE: True
MISC:
  VERBOSE: False
  FAST_DEV_RUN: False
  NUM_GPUS: [0, 3]
  OUTPUT_DIR: /home/abrsh/benchmark/release1_clips_extraction
  TEST_TRAIN_CODE: False
SLOWFAST:
  ALPHA: 8
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[1, 3], []], [[1, 3, 5], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[ [ 1, 2, 2 ], [ 1, 2, 2 ] ], [ [ 1, 2, 2 ], [ 1, 2, 2 ] ], [ [ 1, 2, 2 ], [ 1, 2, 2 ] ], [ [ 1, 2, 2 ], [ 1, 2, 2 ] ], ]
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: [2]
  ARCH: slowfast
  MODEL_NAME: ViViT
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5

VIVIT:
  PATCH_SIZE: 16
  DIM: 32
  DEPTH: 12
  HEADS: 12
  MLP_DIM: 2048
  DIM_HEAD: 3072